cc_binary(
    name = "cc_version",
    srcs = [
        "main.cpp",
    ],
    deps = [
        "//examples/git_version:cc_version",
    ],
    copts = [
        "-std=c++11",
        "-Wall",
    ],
)
