load("//git_version:version.bzl", "cc_git_version")
load("//git_version:go_version.bzl", "go_git_version")

cc_git_version(
    visibility = ["//visibility:public"],
)

go_git_version(
    visibility = ["//visibility:public"],
)
